### ISSUE TITLE
"exceeded"

### ISSUE THREAD

**Issue by realfan2020** [Michele0303/InstagramWatcherBot#1]
Hello Dear

Eeveríthing works fine, but after a few hours, the application stops and says the following:
"context deadline exceeded"
What can be the solution?
Thank you

**Comment by realfan2020** [comment]
Now I have this errorr message:
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.getIdFromUser({0xc0001480d0, 0xc})
        C:/Users/tender/InstagramWatcherBot/instabot.go:75 +0x297
main.runBot(0xa1dae0?)
        C:/Users/tender/InstagramWatcherBot/instabot.go:32 +0xd5
main.main()
        C:/Users/tender/InstagramWatcherBot/main.go:37 +0x3a6

How can I fix it?
Thank you!

**Comment by Michele0303** [comment]
Can you provide the entire error regarding context deadline exceeded?

**Comment by realfan2020** [comment]
Hello, I still have a problem:

░▀█▀░█▀▀░░░█░█░█▀█░▀█▀░█▀▀░█░█░█▀▀░█▀▄░░░█▀▄░█▀█░▀█▀
░░█░░█░█░░░█▄█░█▀█░░█░░█░░░█▀█░█▀▀░█▀▄░░░█▀▄░█░█░░█░
░▀▀▀░▀▀▀░░░▀░▀░▀░▀░░▀░░▀▀▀░▀░▀░▀▀▀░▀░▀░░░▀▀░░▀▀▀░░▀░

[*] TelegramBot successfully configured
[*] HttpClient successfully configured
[*] WatchList -> [elonmusk zuck thisisbillgates]

[*] Bot Started!

panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.getIdFromUser({0xc000022660, 0x8})
        C:/Users/Béci/InstagramWatcherBot/instabot.go:79 +0x31c
main.runBot(0xb9db20?)
        C:/Users/Béci/InstagramWatcherBot/instabot.go:32 +0xd5
main.main()
        C:/Users/Béci/InstagramWatcherBot/main.go:37 +0x3a6

**Comment by mare91su** [comment]
hello, i have the problem when i start the .exe it opens and just closes after few seconds, but says t is all ok, no errors...


░▀█▀░█▀▀░░░█░█░█▀█░▀█▀░█▀▀░█░█░█▀▀░█▀▄░░░█▀▄░█▀█░▀█▀
░░█░░█░█░░░█▄█░█▀█░░█░░█░░░█▀█░█▀▀░█▀▄░░░█▀▄░█░█░░█░
░▀▀▀░▀▀▀░░░▀░▀░▀░▀░░▀░░▀▀▀░▀░▀░▀▀▀░▀░▀░░░▀▀░░▀▀▀░░▀░

[] TelegramBot successfully configured
[] HttpClient successfully configured
[*] WatchList -> [elonmusk zuck thisisbillgates]

[*] Bot Started!
